from core.vector_db import forum_embeddings
import datetime


class ForumEmbedding:
    collection = forum_embeddings

    @staticmethod
    def add(embed_id, embedding, document_text, post_id, type_,
            topic, category, reply_id=None, score=0.0,
            is_accepted=False):
        """
        Stores a vector embedding for a forum item.
        - embed_id      : unique embedding identifier
        - embedding     : Float1024 vector generated by BAAI/bge-m3
        - document_text : original text (question, answer, or summary)
        - post_id       : MongoDB ObjectId of the post
        - type_         : "question" | "answer" | "summary"
        - topic         : related subject/topic
        - category      : "Academic" | "General"
        - reply_id      : MongoDB ObjectId of the reply (if applicable)
        - score         : average rating score
        - is_accepted   : whether the answer is accepted
        """
        now = datetime.datetime.utcnow().isoformat()

        print("[DEBUG] ForumEmbedding.add -> embed_id:", embed_id)
        print("[DEBUG] type:", type_, "category:", category, "topic:", topic)

        forum_embeddings.add(
            ids=[embed_id],
            embeddings=[embedding],
            documents=[document_text],
            metadatas=[{
                "postId":      str(post_id),
                "replyId":     str(reply_id) if reply_id else "",
                "type":        type_,
                "topic":       topic,
                "category":    category,
                "score":       score,
                "isAccepted":  is_accepted,
                "createdAt":   now,
                "updatedAt":   now,
            }]
        )

        print("[DEBUG] ForumEmbedding.add -> stored successfully")


    @staticmethod
    def search(query_embedding, n_results=5):
        print("[DEBUG] ForumEmbedding.search -> n_results:", n_results)

        results = forum_embeddings.query(
            query_embeddings=[query_embedding],
            n_results=n_results,
            include=["documents", "metadatas", "distances"]
        )

        print("[DEBUG] ForumEmbedding.search -> results:", results)

        return results



    @staticmethod
    def search_duplicates(query_embedding, n_results=5):
        """
        Detects similar questions before posting.
        Only searches where type = question.
        """
        print("[DEBUG] ForumEmbedding.search_duplicates -> n_results:", n_results)

        results = forum_embeddings.query(
            query_embeddings=[query_embedding],
            n_results=n_results,
            where={"type": "question"},
            include=["documents", "metadatas", "distances"]
        )

        print("[DEBUG] ForumEmbedding.search_duplicates -> results:", results)

        return results



    @staticmethod
    def search_by_category(query_embedding, category, n_results=5):
        print("[DEBUG] ForumEmbedding.search_by_category -> category:", category)

        results = forum_embeddings.query(
            query_embeddings=[query_embedding],
            n_results=n_results,
            where={"category": category},
            include=["documents", "metadatas", "distances"]
        )

        print("[DEBUG] ForumEmbedding.search_by_category -> results:", results)

        return results


    @staticmethod
    def update_score(embed_id, new_score, updated_at=None):
        print("[DEBUG] ForumEmbedding.update_score -> embed_id:", embed_id)
        print("[DEBUG] new_score:", new_score)

        forum_embeddings.update(
            ids=[embed_id],
            metadatas=[{
                "score":     new_score,
                "updatedAt": updated_at or datetime.datetime.utcnow().isoformat(),
            }]
        )

        print("[DEBUG] ForumEmbedding.update_score -> updated successfully")


    @staticmethod
    def delete(embed_id):
        print("[DEBUG] ForumEmbedding.delete -> embed_id:", embed_id)

        forum_embeddings.delete(ids=[embed_id])

        print("[DEBUG] ForumEmbedding.delete -> deleted successfully")


    @staticmethod
    def count():
        result = forum_embeddings.count()

        print("[DEBUG] ForumEmbedding.count -> total:", result)

        return result