import chromadb
from django.conf import settings

print("[DEBUG] Initializing ChromaDB client with path:", settings.CHROMA_PATH)

client = chromadb.PersistentClient(path=settings.CHROMA_PATH)

# Collection 1: chat_embeddings
# Vectorized chunks from books and academic guides.
# Fields:
#   id               : UUID/String      → Unique chunk identifier
#   embedding        : Float1024 Vector → Generated by BAAI/bge-m3
#   document_text    : String           → Text content of the chunk
#   metadata_source  : String           → PDF name or book title
#   metadata_page    : Integer          → Source page number

print("[DEBUG] Creating or loading collection: chat_embeddings")

chat_embeddings = client.get_or_create_collection(
    name="chat_embeddings",
    metadata={
        "description": "Vectorized fragments of books and academic guides for Systems Engineering program",
        "embedding_model": "BAAI/bge-m3",
        "embedding_dimensions": 1024,
        "hnsw:space": "cosine",
    }
)

print("[DEBUG] chat_embeddings collection ready")

# Collection 2: forum_embeddings
# Vectorized forum questions, answers, and summaries.
# Fields:
#   id                  : UUID/String      → Unique embedding identifier
#   embedding           : Float1024 Vector → Generated by BAAI/bge-m3
#   document_text       : String           → Original text (question, answer, or summary)
#   metadata_postId     : ObjectId         → MongoDB post ID
#   metadata_replyId    : ObjectId/null    → MongoDB reply ID (if applicable)
#   metadata_type       : String           → "question" | "answer" | "summary"
#   metadata_topic      : String           → Related subject/topic
#   metadata_category   : String           → "Academic" | "General"
#   metadata_score      : Float            → Average rating score
#   metadata_isAccepted : Boolean          → Whether the answer is accepted
#   metadata_createdAt  : Date             → Creation timestamp
#   metadata_updatedAt  : Date             → Last update timestamp

print("[DEBUG] Creating or loading collection: forum_embeddings")

forum_embeddings = client.get_or_create_collection(
    name="forum_embeddings",
    metadata={
        "description": "Vectorized forum questions, answers, and summaries for semantic search and duplicate detection",
        "embedding_model": "BAAI/bge-m3",
        "embedding_dimensions": 1024,
        "hnsw:space": "cosine",
    }
)

print("[DEBUG] forum_embeddings collection ready")