from core.vector_db import chat_embeddings
import datetime


class ChatEmbedding:
    collection = chat_embeddings

    @staticmethod
    def add(chunk_id, embedding, document_text, source, page):
        """
        Adds a vectorized chunk from a book or academic guide.
        - chunk_id      : unique identifier of the chunk
        - embedding     : Float1024 vector generated by BAAI/bge-m3
        - document_text : textual content of the chunk
        - source        : PDF name or book title
        - page          : source page number
        """
        print("[DEBUG] ChatEmbedding.add -> chunk_id:", chunk_id)
        print("[DEBUG] source:", source, "page:", page)

        chat_embeddings.add(
            ids=[chunk_id],
            embeddings=[embedding],
            documents=[document_text],
            metadatas=[{
                "source": source,
                "page":   page,
            }]
        )

        print("[DEBUG] ChatEmbedding.add -> stored successfully")

    @staticmethod
    def search(query_embedding, n_results=5, source=None):
        print("[DEBUG] ChatEmbedding.search -> n_results:", n_results, "source:", source)

        where = {"source": source} if source else None

        results = chat_embeddings.query(
            query_embeddings=[query_embedding],
            n_results=n_results,
            where=where,
            include=["documents", "metadatas", "distances"]
        )

        print("[DEBUG] ChatEmbedding.search -> results:", results)

        return results


    @staticmethod
    def delete(chunk_id):
        print("[DEBUG] ChatEmbedding.delete -> chunk_id:", chunk_id)

        chat_embeddings.delete(ids=[chunk_id])

        print("[DEBUG] ChatEmbedding.delete -> deleted successfully")

    @staticmethod
    def count():
        result = chat_embeddings.count()

        print("[DEBUG] ChatEmbedding.count -> total:", result)

        return result